INSERT INTO CARGO (NOME_CARGO) VALUES ('GERENTE');
INSERT INTO CARGO (NOME_CARGO) VALUES ('FISCAL');

INSERT INTO PERFIL (NOME_PERFIL) VALUES ('ADMINISTRADOR');
INSERT INTO PERFIL (NOME_PERFIL) VALUES ('NORMAL');

INSERT INTO USUARIO(NOME_USUARIO, CPF, SEXO, DATA_NASCIMENTO, ID_CARGO, ID_PERFIL, STATUS) VALUES ('VICTOR', '11113212402', 'M', '2019-05-05', 1, 1, 'ATIVO');
INSERT INTO USUARIO(NOME_USUARIO, CPF, SEXO, DATA_NASCIMENTO, ID_CARGO, ID_PERFIL, STATUS) VALUES ('Usuario1', '01370444702', 'F', '2001-12-25', 1, 2, 'ATIVO');

